fix: Buttons final design QA
flocasts/flo-scss pull request #26
Opened 2020-02-25 20:23 UTC by matttelliott-flosports

2020-03-06 20:53 UTC, ArianneArcher commented
Will need to pull to doa complete design review

2020-03-09 02:55 UTC, ArianneArcher requested changes
In-depth and detailed updates for primary, secondary , outline btns and sizes documented in Jira ticket.  

Jira Link: https://flocasts.atlassian.net/browse/FLO-11030

**Update Highlights**
- Remove gradients
- update border-radius
- update :active, :hover, :focus

2020-03-09 02:55 UTC, ArianneArcher commented on scss/_variables.scss
> +$btn-border-radius: from-pixels(6) !default;
from-pixels(5)

2020-03-09 02:55 UTC, ArianneArcher commented on scss/_variables.scss
> +$btn-border-radius: from-pixels(6) !default;
from-pixels changes px value to the rem then on all mobile, Tablet, desktop 

button-radius: 5px
from-pixeles(5)

2020-03-09 02:55 UTC, ArianneArcher commented on site/docs/components/buttons.md
>  description: Use Bootstrap's custom button styles for actions in forms, dialogs, and more with support for multiple sizes, states, and more.
description: overriding bootstrap btns with FloSports brand. This will reflect in forms, dialogs, and more with support for multiple sizes, states, and more.

2020-03-20 22:42 UTC, ArianneArcher commented on scss/_variables.scss
> +$btn-border-radius: from-pixels(6) !default;
STATUS : Changes still needed. Slacked Chris

2020-03-26 21:21 UTC, ArianneArcher commented on scss/_variables.scss
> +$btn-border-radius: from-pixels(6) !default;
STATUS:  In a good place to merge in typography changes. Then heights on btns will be reviewed

2020-03-27 22:39 UTC, ArianneArcher commented
Last round on Design review changes submitted. **Looking good** on my end. 
Just pull the latest changes and if it looks correct on your end go ahead and merge. 

_(If you make and more changes then just let me know to take another gander.)_

2020-03-30 15:38 UTC, bexux approved these changes

2020-03-30 16:00 UTC, ArianneArcher approved these changes

2020-03-30 16:19 UTC, merged

2020-03-31 14:57 UTC, matttelliott-flosports commented
:tada: This PR is included in version 0.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@flosportsinc/flo-scss/v/0.5.0)
- [GitHub release](https://github.com/flocasts/flo-scss/releases/tag/v0.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: